HH.web/Controllers/MissionController.cs
using HH.bll.DTOs.MissionDTO;
using HH.bll.Services.LanguageService;
using HH.bll.Services.MissionService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace HH.web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class MissionController : Controller
    {
        private readonly IMissionService _missionService;
        private readonly ILanguageService _languageService;

        public MissionController(IMissionService missionService, ILanguageService languageService)
        {
            _missionService = missionService;
            _languageService = languageService;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Languages = _languageService.GetAllPublishLanguage().OrderBy(o => o.DisplayOrder);
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateMissionDTO mission)
        {
            if (ModelState.IsValid)
            {
                await _missionService.CreateMission(mission);

                return RedirectToAction("Index");
            }
            ViewBag.Languages = _languageService.GetAllPublishLanguage().OrderBy(o => o.DisplayOrder);
            return View(mission);
        }
        [HttpGet]

        public async Task<IActionResult> Edit(int id)
        {
            var mission = await _missionService.GetMissionForEditById(id);
            if (mission == null)
            {
                return NotFound();
            }
            ViewBag.Languages = _languageService.GetAllPublishLanguage().OrderBy(o => o.DisplayOrder);
            return View(mission);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(EditMissionDTO editMissionDTO)
        {
            if (ModelState.IsValid)
            {
                await _missionService.EditMission(editMissionDTO);
                return RedirectToAction("Index");
            }
            ViewBag.Languages = _languageService.GetAllPublishLanguage().OrderBy(o => o.DisplayOrder);
            return View(editMissionDTO);
        }
        public IActionResult Delete(int? id)
        {
            ViewBag.Languages = _languageService.GetAllPublishLanguage().OrderBy(o => o.DisplayOrder);
            return View();
        }
    }
}

HH.web/Views/Mission/Create.cshtml
@model HH.bll.DTOs.MissionDTO.CreateMissionDTO
@using HH.web
@using HH.bll.DTOs.LanguageDTO
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@inject IHtmlLocalizer<SharedResource> SharedLocalizer

@{
    ViewData["Title"] = SharedLocalizer["Create mission"];

    int lngIndex = 0;

}

<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                @SharedLocalizer["Create mission"]
            </h1>
        </div>
    </div>
    <div class="row" >
        <div class="col-lg-12" >
                <form asp-action="Create" id="form" enctype="multipart/form-data">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <div class="form-row">
                        <div class="col-lg-6">
                            @foreach (LanguageDTO languageDTO in ViewBag.Languages)
                            {
                                <h2>@languageDTO.Name</h2>
                                <hr />
                                <input type="hidden" class="form-control" name="MissionTranslates[@lngIndex].LanguageCulture" value="@languageDTO.Culture" />                                                         
                                    <label>@SharedLocalizer["Name"] *</label>
                                    <div id="name-@lngIndex"></div>
                                    <label>@SharedLocalizer["Description"] *</label>
                                    <div id="description-editor-@lngIndex"></div>
                                    <script>
                                    $( function() {
                                        $("#name-@lngIndex").dxTextBox({
                                            name: "MissionTranslates[@lngIndex].Name"
                                        }).dxValidator({
                                            validationRules: [{
                                                type: "required",
                                                message: '@SharedLocalizer["Enter"]'
                                            }]
                                        });
                                        $("#description-editor-@lngIndex").dxHtmlEditor({
                                            height: 250,
                                            toolbar: {
                                                items: [
                                                    "undo", "redo", "separator",
                                                    {
                                                        formatName: "header",
                                                        formatValues: [false, 1, 2, 3, 4, 5]
                                                    },
                                                    {
                                                        formatName: "size",
                                                        formatValues: ["8pt", "10pt", "12pt", "14pt", "18pt", "24pt", "36pt"]
                                                    },
                                                    {
                                                    formatName: "font",
                                                    formatValues: ['Arial', 'Courier New', 'Georgia', 'Impact', 'Lucida Console', 'Tahoma', 'Times New Roman', 'Verdana', 'IBM Plex Sans'],
                                                     },
                                                        "bold", "italic", "strike", "underline", "separator",
                                                             "alignLeft", "alignCenter", "alignRight", "alignJustify", "separator",
                                                              "orderedList", "bulletList", "separator",
                                                              "color", "background", "separator",
                                                               "link", "image", "separator",
                                                               "clear", "codeBlock", "blockquote",
                                                    {
                                                        widget: "dxButton",
                                                        options: {
                                                            text: "Show markup",
                                                            stylingMode: "text",
                                                            onClick: function () {
                                                                popupInstance.show();
                                                            }
                                                        }
                                                    }
                                                ]
                                            },
                                            name: `MissionTranslates[@lngIndex].Description`,
                                        }).dxHtmlEditor("instance");
                                    });
                                </script>

                                lngIndex++;
                            }
                        </div>
                        <div class="col-lg-6"> 
                            <h2>@SharedLocalizer["Data"]</h2>
                            <hr />
                            <div class="form-group">
                                <label>@SharedLocalizer["Icon"] *</label>
                                <div id="icon"></div>
                            </div>
                            <div class="form-group">
                                <label>@SharedLocalizer["Icon Code"] *</label>
                                <input type="text" class="form-control" name="iconCode" />
                            </div>  
                              <div class="form-group">
                                <div id="published"></div>
                            </div>                        
                       </div>
                </div>
                 <div class="dx-fieldset">
                    <br />
                    <div id="summary"></div>
                    <br />
                    <div id="button"></div>
                </div>
            </form>
          </div>
      </div>
</div>
@section Scripts {
    <script>
     $(function () {
         $("#icon").dxFileUploader({
                selectButtonText: '@SharedLocalizer["Choose a picture"]',
                name: "FormIcon",
                labelText: '@SharedLocalizer["or drag picture"]',
                accept: "image/*",
                uploadMode: "or drag",
                multiple: false,
            }).dxValidator({
                validationRules: [{
                    type: "required",
                    message: '@SharedLocalizer["Upload picture"]'
                }]
            });
         $("#published").dxCheckBox({
                value: true,
                text: '@SharedLocalizer["Active"]',
                name: 'IsPublish',
            });
          $("#button").dxButton({
                text: '@SharedLocalizer["Add"]',
                type: "success",
                useSubmitBehavior: true,
            });
            $("#summary").dxValidationSummary({});
        });
        </script>
}

HH.web/Views/Mission/Edit.cshtml
@model HH.bll.DTOs.MissionDTO.EditMissionDTO
@using HH.web
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@inject IHtmlLocalizer<SharedResource> SharedLocalizer
@using HH.bll.DTOs.LanguageDTO

@{
    ViewData["Title"] = SharedLocalizer["Edit mission"];


    int lngIndex = 0;
}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                @SharedLocalizer["Edit mission"]
            </h1>
        </div>
    </div>

    <div class="row">
        <div class="col-lg-12">
            <form asp-action="Edit" id="form" enctype="multipart/form-data">
                    <div asp-validation-summary="All" class="text-danger"></div>
                    <input type="hidden" asp-for="Id" />
                    <div class="form-row">
                        <div class="col-lg-6">
                            @foreach (LanguageDTO languageDTO in ViewBag.Languages)
                            {
                                <h2>@languageDTO.Name</h2>
                                <hr />
                                {
                                    var missionT = Model.MissionTranslates.FirstOrDefault(p => p.LanguageCulture == languageDTO.Culture);

                                    if (missionT != null)
                                    {
                                        <input type="hidden" name="MissionTranslates[@lngIndex].Id" value="@missionT.Id" />
                                        <input type="hidden" class="form-control" name="MissionTranslates[@lngIndex].LanguageCulture" value="@languageDTO.Culture" />
                                        <div class="form-group">
                                            <label>@SharedLocalizer["Name"] *</label>
                                            <input type="text" class="form-control" name="MissionTranslates[@lngIndex].Name" value="@missionT.Name" />
                                        </div>                                       
                                        <label>@SharedLocalizer["Description"] *</label>
                                        <div id="description-editorr-@lngIndex"></div>
                              
                                    }
                                    <script>
                                    $( function() {
                                        $("#description-editorr-@lngIndex").dxHtmlEditor({
                                            height: 250,
                                            toolbar: {
                                                items: [
                                                    "undo", "redo", "separator",
                                                    {
                                                        formatName: "header",
                                                        formatValues: [false, 1, 2, 3, 4, 5]
                                                    },
                                                    {
                                                        formatName: "size",
                                                        formatValues: ["8pt", "10pt", "12pt", "14pt", "18pt", "24pt", "36pt"]
                                                    },
                                                    {
                                                    formatName: "font",
                                                    formatValues: ['Arial', 'Courier New', 'Georgia', 'Impact', 'Lucida Console', 'Tahoma', 'Times New Roman', 'Verdana', 'IBM Plex Sans'],
                                                     },
                                                        "bold", "italic", "strike", "underline", "separator",
                                                             "alignLeft", "alignCenter", "alignRight", "alignJustify", "separator",
                                                              "orderedList", "bulletList", "separator",
                                                              "color", "background", "separator",
                                                               "link", "image", "separator",
                                                               "clear", "codeBlock", "blockquote",
                                                    {
                                                        widget: "dxButton",
                                                        options: {
                                                            text: "Show markup",
                                                            stylingMode: "text",
                                                            onClick: function () {
                                                                popupInstance.show();
                                                            }
                                                        }
                                                    }
                                                ]
                                            },
                                            name: `MissionTranslates[@lngIndex].Description`,
                                            value: @Json.Serialize(@missionT.Description),
                                        }).dxHtmlEditor("instance");
                                    });
                                </script>
                                }

                                lngIndex++;
                            }   

                        </div>
                            <div class="col-lg-6">
                            <h2>@SharedLocalizer["Data"]</h2>
                            <hr />
                                                        
                            <div class="form-group">
                                <label>@SharedLocalizer["Icon"] *</label>
                                <div id="image"></div>
                            </div>
                            @if (Model.Icon != null && Model.Icon.Length > 0)
                            {
                                <img src="~/images/mission/@Model.Icon" class="img-responsive img-thumbnail" style="width: 130px;" />
                            }
                            <input type="hidden" name="Icon" value="@Model.Icon" />
                            <div class="form-group">
                                <label>@SharedLocalizer["Icon Code"] *</label>
                                <input type="text" class="form-control" name="iconCode" value="@Model.iconCode" />
                            </div>
                                <div class="form-group">
                                <div id="published"></div>
                            </div>
                        </div>
                    </div>

               
                <div class="dx-fieldset">
                    <br />
                    <div id="summary"></div>
                    <br />
                    <div id="button"></div>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(function () {
            
            $("#image").dxFileUploader({
                                            selectButtonText: '@SharedLocalizer["Choose a picture"]',
                                            name: "FormIcon",
                                            labelText: '@SharedLocalizer["or drag picture"]',
                                            accept: "image/*",
                                            uploadMode: '@SharedLocalizer["or drag"]',
                                            multiple: false,
                                        });

            let published = '@Model.IsPublish';
            $("#published").dxCheckBox({
                value: (published.toLowerCase() == 'true'),
                text: '@SharedLocalizer["Active"]',
                name: 'IsPublish',
            });

            $("#button").dxButton({
                text: '@SharedLocalizer["Edit"]',
                type: "success",
                useSubmitBehavior: true,
            });
            $("#summary").dxValidationSummary({});
        });
    </script>

}

HH.web/Views/Mission/Index.cshtml
@using HH.web.Utilities;
@using HH.web
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@inject IHtmlLocalizer<SharedResource> SharedLocalizer

@{
    ViewData["Title"] = SharedLocalizer["Missions"];

}

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                @SharedLocalizer["Missions"] 
            </h1>
        </div>
    </div>

    <div class="row">
        <div id="gridContainer">
        </div>
    </div>
</div>

@section Scripts{
    <script>
        $(function () {
            let url = `@API.GetAllMission`;
            var returnUrl = '@Context.Request.Path@Context.Request.QueryString';
            $("#gridContainer").dxDataGrid({
                dataSource: DevExpress.data.AspNet.createStore({
                    key: "id",
                    loadUrl: url,
                    insertUrl: url,
                    updateUrl: url,
                    deleteUrl: url,
                    onBeforeSend: function (method, ajaxOptions) {
                        ajaxOptions.xhrFields = { withCredentials: true };
                    }
                }),
                onInitNewRow: function(e) {
                    var url = `@Url.Action("Create", "Mission")`;
                    window.location = url;
                },
                filterPanel: {
                    visible: false
                },
                filterRow: { visible: false },
                remoteOperations: true,
                onRowUpdating: function (e) {
                    e.newData = Object.assign(e.oldData, e.newData)
                },
                scrolling: {
                    mode: "virtual",
                    rowRenderingMode: "virtual"
                },
                paging: {
                    pageSize: 100
                },
                editing: {
                    useIcons: true,
                    allowUpdating: true,
                    allowDeleting: true,
                    allowAdding: true
                },
                headerFilter: {
                    visible: true
                },
                wordWrapEnabled: true,
                showColumnLines: true,
                showRowLines: true,
                rowAlternationEnabled: true,
                showBorders: true,
                searchPanel: {
                    visible: true
                },
                stateStoring: {
                    enabled: true,
                    type: "localStorage",
                    storageKey: "MissionAdmin"
                },
                columns: [
                    {
                        caption: '@SharedLocalizer["Name"]',
                        dataField: "name",
                        allowHeaderFiltering: false
                    },                   
                    {
                        caption: '@SharedLocalizer["Description"]',
                        dataField: "description",
                        allowHeaderFiltering: false
                    },
                     {
                        caption: '@SharedLocalizer["Icon"]',
                        dataField: "icon",
                        allowHeaderFiltering: false
                    },
                    { 
                        caption: '@SharedLocalizer["Icon Code"]',
                        dataField: "iconCode",
                        allowHeaderFiltering: false
                    },
                     {
                        caption: '@SharedLocalizer["Active"]',
                        dataField: "isPublish",
                        width: "130",
                        allowHeaderFiltering: false
                    },
                    {
                        type: "buttons",
                        width: 110,
                        buttons: [
                            {
                                hint: '@SharedLocalizer["Edit"]',
                                icon: "edit",
                                onClick: function (e) {
                                    var idString = e.row.data.id;
                                    var url = `@Url.Action("Edit", "Mission")`;
                                    window.location = url + '?id=' + idString;
                                }
                            },
                            "delete"
                        ]
                    }
                ]
            });

        });
    </script>
}