HH.web/Controllers/AboutUsController.cs
using AutoMapper;
using HH.bll.DTOs.AboutUsDTO;
using HH.bll.Services.AboutUsService;
using HH.bll.Services.LanguageService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace HH.web.Controllers
{
 
    [Authorize(Roles = "Admin")]
    public class AboutUsController : Controller
    {
        private readonly IAboutUsService _aboutService;
        private readonly ILanguageService _languageService;
        private readonly IMapper _mapper;

        public AboutUsController(IAboutUsService aboutService, ILanguageService languageService, IMapper mapper)
        {
            _aboutService = aboutService;
            _languageService = languageService;
            _mapper = mapper;   
        }

         public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Create()   
        {
            ViewBag.Languages = _languageService.GetAllPublishLanguage().OrderBy(o => o.DisplayOrder);
            return View();
        }
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateAboutUsDTO aboutUs)
        {
            if (ModelState.IsValid)
            {
                await _aboutService.CreateAbout(aboutUs);

                return RedirectToAction("Index");
            }
            ViewBag.Languages = _languageService.GetAllPublishLanguage().OrderBy(o => o.DisplayOrder);
            return View(aboutUs);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var about = await _aboutService.GetAboutUsForEditById(id);
            if (about == null)
            {
                return NotFound();
            }
            ViewBag.Languages = _languageService.GetAllPublishLanguage().OrderBy(o => o.DisplayOrder);
            return View(about);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(EditAboutUsDTO editAboutUsDTO)
        {
            if (ModelState.IsValid)
            {
                await _aboutService.EditAbout(editAboutUsDTO);
                return RedirectToAction("Index");
            }
            ViewBag.Languages = _languageService.GetAllPublishLanguage().OrderBy(o => o.DisplayOrder);
            return View(editAboutUsDTO);
        }
        public IActionResult Delete(int? id)
        {
            ViewBag.Languages = _languageService.GetAllPublishLanguage().OrderBy(o => o.DisplayOrder);
            return View();
        }

    }
}

HH.web/Controllers/BannerController.cs
using HH.bll.DTOs.BannerDTO;
using HH.bll.Services.BannerService;
using HH.bll.Services.LanguageService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace HH.web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BannerController : Controller
    {
        private readonly IBannerService _bannerService;
        private readonly ILanguageService _languageService;
        public BannerController(IBannerService bannerService, ILanguageService languageService)
        {
            _bannerService = bannerService;
            _languageService = languageService;
        }
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Create()
        {
            ViewBag.Languages = _languageService.GetAllPublishLanguage().OrderBy(o => o.DisplayOrder);
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateBannerDTO banner)
        {
            if (ModelState.IsValid)
            {
                await _bannerService.CreateBanner(banner);

                return RedirectToAction("Index");
            }
            ViewBag.Languages = _languageService.GetAllPublishLanguage().OrderBy(o => o.DisplayOrder);
            return View(banner);
        }
        [HttpGet]
        
        public async Task<IActionResult> Edit(int id)
        {
            var about = await _bannerService.GetBannerForEditById(id);
            if (about == null)
            {
                return NotFound();
            }
            ViewBag.Languages = _languageService.GetAllPublishLanguage().OrderBy(o => o.DisplayOrder);
            return View(about);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(EditBannerDTO editAboutUsDTO)
        {
            if (ModelState.IsValid)
            {
                await _bannerService.EditBanner(editAboutUsDTO);
                return RedirectToAction("Index");
            }
            ViewBag.Languages = _languageService.GetAllPublishLanguage().OrderBy(o => o.DisplayOrder);
            return View(editAboutUsDTO);
        }
        public IActionResult Delete(int? id)
        {
            ViewBag.Languages = _languageService.GetAllPublishLanguage().OrderBy(o => o.DisplayOrder);
            return View();
        }
    }
}

HH.web/Controllers/ClientController.cs
using HH.bll.DTOs.ClientDTO;
using HH.bll.Services.ClientService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace HH.web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class ClientController : Controller
    {
        private readonly IClientService _clientService;

        public ClientController(IClientService clientService)
        {
            _clientService = clientService;
        }

         public IActionResult Index()
         {
            return View();
         }
         [HttpGet]
         public IActionResult Create()
         {
            return View();
         }
         [HttpPost]
        public async Task<IActionResult> Create(CreateClientDTO client)
        {
            if (ModelState.IsValid)
            {
                await _clientService.CreatClient(client);

                return RedirectToAction("Index");
            }
            return View(client);
        }
        [HttpGet]

        public async Task<IActionResult> Edit(int id)
        {
            var about = await _clientService.GetClientForEditById(id);
            if (about == null)
            {
                return NotFound();
            }
            return View(about);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(EditClientDTO editAboutUsDTO)
        {
            if (ModelState.IsValid)
            {
                await _clientService.EditClient(editAboutUsDTO);
                return RedirectToAction("Index");
            }
            return View(editAboutUsDTO);
        }
        public IActionResult Delete(int? id)
        {
            return View();
        }

    }
}

HH.web/Controllers/CompanyController.cs
using HH.bll.DTOs.CompanyDTO;
using HH.bll.Services.CompanyService;
using HH.bll.Services.LanguageService;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace HH.web.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CompanyController : Controller
    {
        private readonly ICompanyService _companyService;
        private readonly ILanguageService _languageService;

        public CompanyController(ICompanyService companyService, ILanguageService languageService)
        {
            _companyService = companyService;
            _languageService = languageService;
        }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Create()
        {
            ViewBag.Languages = _languageService.GetAllPublishLanguage().OrderBy(o => o.DisplayOrder);
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateNewsDTO news)
        {
            if (ModelState.IsValid)
            {
                await _companyService.CreateNews(news);

                return RedirectToAction("Index");
            }
            ViewBag.Languages = _languageService.GetAllPublishLanguage().OrderBy(o => o.DisplayOrder);
            return View(news);
        }
        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var news = await _companyService.GetNewsForEditById(id);
            if (news == null)
            {
                return NotFound();
            }
            ViewBag.Languages = _languageService.GetAllPublishLanguage().OrderBy(o => o.DisplayOrder);
            return View(news);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(EditNewsDTO editNewsDTO)
        {
            if (ModelState.IsValid)
            {
                await _companyService.EditNews(editNewsDTO);
                return RedirectToAction("Index");
            }
            ViewBag.Languages = _languageService.GetAllPublishLanguage().OrderBy(o => o.DisplayOrder);
            return View(editNewsDTO);
        }
        //public IActionResult Delete(int? id)
        //{
        //    ViewBag.Languages = _languageService.GetAllPublishLanguage().OrderBy(o => o.DisplayOrder);
        //    return View();
        //}
        public IActionResult License()
        {
            return View();
        }
        public IActionResult CreateLicense()
        {
            ViewBag.Languages = _languageService.GetAllPublishLanguage().OrderBy(o => o.DisplayOrder);
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateLicense(CreateLicenseDTO license)
        {
            if (ModelState.IsValid)
            {
                await _companyService.CreateLicense(license);

                return RedirectToAction("License");
            }
            ViewBag.Languages = _languageService.GetAllPublishLanguage().OrderBy(o => o.DisplayOrder);
            return View(license);
        }
        [HttpGet]
        public async Task<IActionResult> EditLicense(int id)
        {
            var license = await _companyService.GetLicenseForEditById(id);
            if (license == null)
            {
                return NotFound();
            }
            ViewBag.Languages = _languageService.GetAllPublishLanguage().OrderBy(o => o.DisplayOrder);
            return View(license);
        }
        [HttpPost]
        public async Task<IActionResult> EditLicense(EditLicenseDTO editLicenseDTO)
        {
            if (ModelState.IsValid)
            {
                await _companyService.EditLicense(editLicenseDTO);
                return RedirectToAction("License");
            }
            ViewBag.Languages = _languageService.GetAllPublishLanguage().OrderBy(o => o.DisplayOrder);
            return View(editLicenseDTO);
        }
    }
}

HH.web/Views/Shared/_Layout.cshtml
@using HH.web
@using System.Globalization;
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer
@inject IHtmlLocalizer<SharedResource> SharedLocalizer

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HH</title>
    <link rel="stylesheet" href="~/client/css/output.css" />
    <link rel="stylesheet" href="~/client/css/pickmeup.css" />
    <link rel="stylesheet" href="~/client/css/swiper.bundle.min.css" />
    <link rel="stylesheet" href="~/client/css/Video.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/fonts/IBMPlexSans/stylesheet.css" />
    @RenderSection("Css", required: false)

    <link rel="stylesheet" href="~/css/site.css" />

    <link href="~/devextreme/css/dx.common.css" rel="stylesheet" />
    <link href="~/devextreme/css/dx.light.css" rel="stylesheet" />

    <script src="~/devextreme/js/jquery.min.js"></script>
    <script src="~/devextreme/js/dx-quill.min.js"></script>
 
    <!-- Styles -->
    <link href="~/assets/css/lib/font-awesome.min.css" rel="stylesheet" />
    <link href="~/assets/css/lib/themify-icons.css" rel="stylesheet" />
    <link href="~/assets/css/lib/owl.theme.default.min.css" rel="stylesheet" />
    <link href="~/assets/css/lib/menubar/sidebar.css" rel="stylesheet" />
    <link href="~/assets/css/lib/bootstrap.min.css" rel="stylesheet" />
    <link href="~/assets/css/lib/helper.css" rel="stylesheet" />
    <link href="~/assets/css/style.css" rel="stylesheet" />
    <style>
        
        .button span {
            cursor: pointer;
            display: inline-block;
            position: relative;
            transition: 0.5s;
        }

            .button span:after {
                content: '\00bb';
                position: absolute;
                opacity: 0;
                top: 0;
                right: -20px;
                transition: 0.5s;
            }

        .button:hover span {
            padding-right: 25px;
        }

            .button:hover span:after {
                opacity: 1;
                right: 0;
            } 
            
    </style>
    
</head>
<body >
    <div class="sidebar  sidebar-hide-to-hide sidebar-shrink sidebar-gestures    ">
        @*sidebar-hide-to-small sidebar-shrink sidebar-gestures*@
            <div class="nano">
                <div class="nano-content">
                    <div class="logo"><a asp-action="Index" asp-controller="Admin">
                                @*<span>Halkara@Hyzmat</span>*@
                                <img src="/logo/logo.svg" />
                                </a></div>
                    <ul>
                        <li><a class="sidebar-sub-toggle">About Us<span
                                class="sidebar-collapse-icon ti-angle-down"></span></a>
                            <ul>
                                <li><a asp-action="Index" asp-controller="AboutUs" >About Us</a></li>
                                <li><a asp-action="Create" asp-controller="AboutUs" >Create</a></li>
                            </ul>
                        </li>
                        <li><a class="sidebar-sub-toggle">Banner<span
                                class="sidebar-collapse-icon ti-angle-down"></span></a>
                            <ul>
                                <li><a asp-action="Index" asp-controller="Banner" >Banner</a></li>
                                <li><a asp-action="Create" asp-controller="Banner" >Create</a></li>
                            </ul>
                        </li>
                          <li><a class="sidebar-sub-toggle">Client<span
                                class="sidebar-collapse-icon ti-angle-down"></span></a>
                            <ul>
                                <li><a asp-action="Index" asp-controller="Client" >Client</a></li>               
                                <li><a asp-action="Create" asp-controller="Client" >Create</a></li>
                            </ul>
                        </li>
                        <li><a class="sidebar-sub-toggle">Company<span
                                class="sidebar-collapse-icon ti-angle-down"></span></a>
                            <ul>
                                <li><a asp-action="Index" asp-controller="Company" >News</a></li>               
                                <li><a asp-action="Create" asp-controller="Company" >Create</a></li>
                                <li><a asp-action="License" asp-controller="Company" >License</a></li>
                                <li><a asp-action="CreateLicense" asp-controller="Company" >Create License</a></li>
                            </ul>
                        </li>
                        <li><a class="sidebar-sub-toggle">Contact<span
                                class="sidebar-collapse-icon ti-angle-down"></span></a>
                            <ul>
                                <li><a asp-action="Index" asp-controller="Contact">Contact</a></li>                                  
                            </ul>
                        </li>
                        <li><a class="sidebar-sub-toggle">Mission<span
                                class="sidebar-collapse-icon ti-angle-down"></span></a>
                            <ul>
                                <li><a asp-action="Index" asp-controller="Mission" >Mission</a></li>               
                                <li><a asp-action="Create" asp-controller="Mission" >Create</a></li>
                            </ul>
                        </li>
                        <li><a class="sidebar-sub-toggle">Product<span
                                class="sidebar-collapse-icon ti-angle-down"></span></a>
                            <ul>
                                <li><a asp-action="Index" asp-controller="Product" >Product</a></li>               
                                <li><a asp-action="Create" asp-controller="Product" >Create</a></li>
                                <li><a asp-action="Option" asp-controller="Product" >Option</a></li>               
                                <li><a asp-action="CreateOption" asp-controller="Product" >Create Option</a></li>
                                <li><a asp-action="CreateOptionContent" asp-controller="Product" >Create Option Content</a></li>
                            </ul>
                        </li>
                        <li><a class="sidebar-sub-toggle">Project<span
                                class="sidebar-collapse-icon ti-angle-down"></span></a>
                            <ul>
                                <li><a asp-action="Index" asp-controller="Project" >Project</a></li>                
                                <li><a asp-action="Create" asp-controller="Project" >Create</a></li>
                                <li><a asp-action="CreateLocation" asp-controller="Project" >Create Location</a></li>
                                <li><a asp-action="CreateStatus" asp-controller="Project" >Create Status</a></li>
                                <li><a asp-action="Location" asp-controller="Project" >Location</a></li>
                                <li><a asp-action="Status" asp-controller="Project" >Status</a></li>
                            </ul>
                        </li>
                        <li><a class="sidebar-sub-toggle">Service<span
                                class="sidebar-collapse-icon ti-angle-down"></span></a>
                            <ul>
                                <li><a asp-action="Index" asp-controller="Service" >Service</a></li>                
                                <li><a asp-action="Create" asp-controller="Service" >Create</a></li>
                            </ul>
                        </li>
                    </ul>
            </div>
        </div>
    </div>
    <div class="header">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="float-left">
                        <div class="hamburger sidebar-toggle">
                            <span class="line"></span>
                            <span class="line"></span>
                            <span class="line"></span>
                        </div>
                    </div>
                    <div class="float-right">
                        <div class="nav-header  z-30 relative order-2">
                         <div class="xl:container xl:px-0 px-4 flex sm:justify-end justify-between h-12">
                    

                    @await Html.PartialAsync("_SelectLanguagePartial")
                    @await Html.PartialAsync("_LoginPartial")

                </div>
                </div>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="content-wrap">        
        @RenderBody()
    </div>
    @*<div  style="margin-left: 250px">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>*@

    <!-- DevExtreme library -->
    
   
    <script src="~/devextreme/js/dx.all.js"></script>
    <script src="~/devextreme/js/localization/dx.messages.ru.js"></script>
    <script src="~/devextreme/js/dx.aspnet.data.js"></script>
    
    <!-- jquery vendor 12 -->
    @*<script src="~/assets/js/lib/jquery.min.js"></script>*@
    <script src="~/assets/js/lib/jquery.nanoscroller.min.js"></script>
    <!-- nano scroller -->
    <script src="~/assets/js/lib/menubar/sidebar.js"></script>
    <script src="~/assets/js/lib/preloader/pace.min.js"></script>
    <!-- sidebar -->
    <script src="~/assets/js/lib/bootstrap.min.js"></script>
    <script src="~/assets/js/scripts.js"></script>
    <!-- bootstrap -->


    <script src="~/client/js/vendor/gsap/gsap.min.js" defer></script>
    <script src="~/client/js/vendor/swiper.min.js"></script>
    <script src="~/client/js/slider.js" defer></script>
    <script src="~/client/js/header.js" defer></script>
    <script src="~/client/js/Video.js" defer></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

HH.web/Views/Shared/_SelectLanguagePartial.cshtml
@using Microsoft.AspNetCore.Builder
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Http.Extensions
@using Microsoft.AspNetCore.Localization
@using Microsoft.AspNetCore.Mvc.Localization
@using Microsoft.Extensions.Options

@inject IViewLocalizer Localizer
@inject IOptions<RequestLocalizationOptions> LocOptions

@{
    // получаем сервис IRequestCultureFeature
    var requestCulture = Context.Features.Get<IRequestCultureFeature>();
    // получаем список поддерживаемых культур
    var cultureItems = LocOptions.Value.SupportedUICultures.Where(p => p.Name != requestCulture.RequestCulture.Culture.Name)
        .Select(c => new SelectListItem { Value = c.Name, Text = c.NativeName.Substring(0, 1).ToUpper() + c.NativeName.Substring(1) })
        .ToList();

    List<SelectListItem> lngListItem = new List<SelectListItem>();
    foreach (var c in cultureItems)
    {
        if (c.Text == "Türkmen dili")
        {
            c.Text = "Türkmen";
        }
        lngListItem.Add(c);
    }
    
}


<div style="text-align: center;" class="text-gray-200 mr-10 select-none select-box relative h-12 flex items-center" id="select-box">
    <div style="width:90px;height: 60px" class="pl-2 flex items-center z-20 bg-dark h-full cursor-pointer">
        @if (requestCulture.RequestCulture.UICulture.NativeName == "türkmen dili")
        {
            <span class="hover:text-white"> Türkmen </span>
        }
        else
        {
            <span class="hover:text-white"> @(requestCulture.RequestCulture.UICulture.NativeName.Substring(0, 1).ToUpper() + requestCulture.RequestCulture.UICulture.NativeName.Substring(1)) </span>
        }

        <svg width="9.73" height="6" viewBox="0 0 9.73 6" class="ml-2" id="select-arrow">
            <path id="path"
                  d="M458.095,877.6l1.135,1.135-4.865,4.865-4.865-4.865,1.135-1.135,3.73,3.73Z"
                  transform="translate(-449.5 -877.6)"
                  fill="#fff"
                  opacity="0.8" />
        </svg>
    </div>
            
    <div style="width:90px; height: 54px;" class="flex flex-col absolute shadow-lg bg-dark pb-4" id="select-content">
        @foreach (var lng in lngListItem)
        {
           
            <a asp-area="" asp-controller="Admin" asp-action="SetLanguage"
               
               asp-route-returnUrl="@Context.Request.GetEncodedPathAndQuery()" asp-route-culture="@lng.Value"
               data-link="#" class="py-1 hover:text-white">@lng.Text</a>
        }
    </div>
</div>